name: Improve existing content
description: Make a suggestion to improve the content in an existing article.
labels:
    - enhancement
body:
    - type: markdown
      attributes:
          value: |
              * Before you file an issue read the [Contributing guide](https://gamedig.github.io/guide/contributing).
              * Check to make sure someone hasn't already opened a similar [issue](https://github.com/gamedig/gamedig.github.io/issues).

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: This project has a Code of Conduct that all participants are expected to understand and follow.
          options:
              - label: I have read and agree to the [Code of Conduct](https://gamedig.github.io/code-of-conduct)
                required: true

    - type: textarea
      attributes:
          label: Article to improve or create
          description: Please link to the article you'd like to see updated.
      validations:
          required: true

    - type: textarea
      attributes:
          label: What part(s) of the article would you like to see updated?
          description: |
              - Give as much detail as you can to help us understand the change you want to see. 
              - Why should the docs be changed? What use cases does it support? 
              - What is the expected outcome or behavior?
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional information
          description: |
              - Are you able to reliably reproduce the problem? How often does it occur? How many users are affected?
              - Add any other context or screenshots about the feature here.
      validations:
          required: false
